In [1]:
import json

file_path = '/projects/bcse/jredepenning/amplfi/runs/hyperparameter_tuning/hyperparameters.json'

In [2]:
with open(file_path, 'r') as file:
    data = json.load(file)

In [4]:
import pandas as pd

df = pd.DataFrame(data)

In [5]:
df

,number,value,params_batch_size,params_batches_per_epoch,params_learning_rate,state
0,0,5.119014,128,100,0.001654,COMPLETE
1,1,5.119042,128,100,0.001198,COMPLETE
2,2,5.142122,128,100,0.003627,COMPLETE
3,3,5.145461,128,150,0.006277,COMPLETE
4,4,5.160021,256,200,0.015740,COMPLETE
5,5,5.133194,256,100,0.008108,PRUNED
6,6,5.124594,512,200,0.001184,COMPLETE
7,7,5.121802,128,100,0.002442,PRUNED
8,8,5.141470,512,150,0.035652,PRUNED
9,9,5.140588,256,150,0.003605,COMPLETE

In [6]:
df.sort_values(by='value', ascending=True)

,number,value,params_batch_size,params_batches_per_epoch,params_learning_rate,state
0,0,5.119014,128,100,0.001654,COMPLETE
1,1,5.119042,128,100,0.001198,COMPLETE
7,7,5.121802,128,100,0.002442,PRUNED
6,6,5.124594,512,200,0.001184,COMPLETE
5,5,5.133194,256,100,0.008108,PRUNED
9,9,5.140588,256,150,0.003605,COMPLETE
8,8,5.141470,512,150,0.035652,PRUNED
2,2,5.142122,128,100,0.003627,COMPLETE
3,3,5.145461,128,150,0.006277,COMPLETE
4,4,5.160021,256,200,0.015740,COMPLETE